// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';

/** Identifier type for public.posts */
export type PostsId = number & { __brand: 'PostsId' };

/** Represents the table public.posts */
export default interface Posts {
  id: PostsId;

  userId: UsersId;

  body: string;

  createdAt: Date;
}

/** Represents the initializer for the table public.posts */
export interface PostsInitializer {
  /** Default value: nextval('posts_id_seq'::regclass) */
  id?: PostsId;

  userId: UsersId;

  body: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;
}

/** Represents the mutator for the table public.posts */
export interface PostsMutator {
  id?: PostsId;

  userId?: UsersId;

  body?: string;

  createdAt?: Date;
}
