// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type MasterProgramId } from './MasterProgram';

/** Identifier type for public.StartYear */
export type StartYearId = number & { __brand: 'StartYearId' };

/** Represents the table public.StartYear */
export default interface StartYear {
  id: StartYearId;

  masterProgramId: MasterProgramId;

  name: string;

  data: string;

  createdAt: Date;
}

/** Represents the initializer for the table public.StartYear */
export interface StartYearInitializer {
  /** Default value: nextval('"StartYear_id_seq"'::regclass) */
  id?: StartYearId;

  masterProgramId: MasterProgramId;

  name: string;

  data: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;
}

/** Represents the mutator for the table public.StartYear */
export interface StartYearMutator {
  id?: StartYearId;

  masterProgramId?: MasterProgramId;

  name?: string;

  data?: string;

  createdAt?: Date;
}
