// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.User */
export type UserId = number & { __brand: 'UserId' };

/** Represents the table public.User */
export default interface User {
  id: UserId;

  name: string;

  email: string;

  createdAt: Date;

  authProvider: string | null;

  authUserId: string | null;
}

/** Represents the initializer for the table public.User */
export interface UserInitializer {
  /** Default value: nextval('"User_id_seq"'::regclass) */
  id?: UserId;

  name: string;

  email: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  authProvider?: string | null;

  authUserId?: string | null;
}

/** Represents the mutator for the table public.User */
export interface UserMutator {
  id?: UserId;

  name?: string;

  email?: string;

  createdAt?: Date;

  authProvider?: string | null;

  authUserId?: string | null;
}
