// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.MasterPlan */
export type MasterPlanId = number & { __brand: 'MasterPlanId' };

/** Represents the table public.MasterPlan */
export default interface DbMasterPlan {
  id: MasterPlanId;

  title: string;

  data: any;

  userId: UserId;
}

/** Represents the initializer for the table public.MasterPlan */
export interface DbMasterPlanInitializer {
  /** Default value: nextval('"MasterPlan_id_seq"'::regclass) */
  id?: MasterPlanId;

  title: string;

  data: any;

  userId: UserId;
}

/** Represents the mutator for the table public.MasterPlan */
export interface DbMasterPlanMutator {
  id?: MasterPlanId;

  title?: string;

  data?: any;

  userId?: UserId;
}
