// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.pgmigrations */
export type PgmigrationsId = number & { __brand: 'PgmigrationsId' };

/** Represents the table public.pgmigrations */
export default interface DbPgmigrations {
  id: PgmigrationsId;

  name: string;

  run_on: Date;
}

/** Represents the initializer for the table public.pgmigrations */
export interface DbPgmigrationsInitializer {
  /** Default value: nextval('pgmigrations_id_seq'::regclass) */
  id?: PgmigrationsId;

  name: string;

  run_on: Date;
}

/** Represents the mutator for the table public.pgmigrations */
export interface DbPgmigrationsMutator {
  id?: PgmigrationsId;

  name?: string;

  run_on?: Date;
}
